language: cpp
compiler: gcc

dist: bionic

addons:
  apt:
    packages:
      - gcc-7
      - g++-7

script:
  - printf "CMAKE : \n"
  - cmake --version
  - printf "\n\nG++ : \n"
  - g++ -v
  - printf "\n\n\nBuilding..."
  - rm -rf ./build
  - mkdir build
  - g++ -c tests/testrunner.cpp -std=c++17 -o build/testrunner.o -DNDEBUG -O2
  - g++ -c main.cpp -std=c++14 -o build/main.o -DNDEBUG -O2
  - cd build
  - g++ testrunner.o main.o -o a.out
  - printf "\n\n\nRunning: \n\n"
  - ./a.out
  - cd ..
  - rm -rf ./build