language: cpp
compiler: gcc

dist: bionic

addons:
  apt:
    packages:
      - gcc-7
      - g++-7

script:
  - cmake --version
  - rm -rf ./build
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make a.out
  - ./a.out
  - cd ..
  - rm -rf ./build