notifications:
  email: false
  
language: cpp
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libopenal-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libudev-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - gcc-7
    - g++-7
    
before_script:
- export SFML_ROOT=$HOME/SFML_LINUX
- pwd
- ls
- git clone https://github.com/SFML/SFML.git
- cd SFML
- cmake -DCMAKE_INSTALL_PREFIX=$SFML_ROOT .
- make
- make install
- cd ..
script:
- export SFML_ROOT=$HOME/SFML_LINUX
- pwd
- ls
- cmake --version
- mkdir build && cd build
- cmake -DSFML_DIR=$SFML_ROOT ..
- make
- tests/EnlivengineTests