language: cpp
dist: bionic
compiler: gcc
  
addons:
  apt:
    packages:
    - cmake
    - libopenal-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libudev-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - gcc
    - g++
    
script:
- pwd
- ls
- cmake --version
- g++ --version
- mkdir build && cd build
- cmake ..
- make
- Enlivengine/EnlivengineTests/EnlivengineTests
- Enlivengine/EnlivengineExamples/SystemExample
