language: cpp
compiler: gcc
os: linux  
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libopenal-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libudev-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - gcc-7
    - g++-7
    
script:
- pwd
- ls
- export CC=gcc-7
- export CXX=g++-7
- g++ --version
- mkdir build && cd build
- cmake --version
- cmake ..
- make
- Enlivengine/EnlivengineTests/EnlivengineTests
- Enlivengine/EnlivengineExamples/SystemExample
