notifications:
  email: false
  
language: cpp
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libopenal-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libudev-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - g++-7
    
script:
- pwd
- ls
- cmake --version
- mkdir build && cd build
- cmake ..
- make
- Enlivengine/EnlivengineTests/EnlivengineTests
- Enlivengine/EnlivengineExamples/SystemExample
