language: cpp
notifications:
  email: false

matrix:
  include:

  - name: "Linux gcc"
    os: linux
    dist: bionic
    compiler: gcc
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - libxrandr-dev
            - libudev-dev
            - libopenal-dev
            - libflac-dev
            - libvorbis-dev
            - libgl1-mesa-dev
            - g++-9
    script:
        - export CXX=g++-9
        - mkdir build && cd build
        - cmake ..
        - make

#  - name: "Linux clang"
#    os: linux
#    dist: bionic
#    compiler: clang
#    addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - cmake
#            - libxrandr-dev
#            - libudev-dev
#            - libopenal-dev
#            - libflac-dev
#            - libvorbis-dev
#            - libgl1-mesa-dev
#    script:
#        - mkdir build && cd build
#        - cmake ..
#        - make

  - name: "macOS Xcode 12"
    os: osx
    osx_image: xcode12
    addons:
        apt:
          packages:
            - cmake
            - libxrandr-dev
            - libudev-dev
            - libopenal-dev
            - libflac-dev
            - libvorbis-dev
            - libgl1-mesa-dev
    script:
        - mkdir build && cd build
        - cmake ..
        - make
    
#  - name: "Visual studio 17 2019"
#    os: windows
#    addons:
#        apt:
#          packages:
#            - cmake
#            - libxrandr-dev
#            - libudev-dev
#            - libopenal-dev
#            - libflac-dev
#            - libvorbis-dev
#            - libgl1-mesa-dev
#    script:
#        - mkdir build && cd build
#        - cmake ..
#        - make