notifications:
  email: false
  
language: 
  - cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libopenal-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libudev-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - gcc-7
    - g++-7
install:
- pwd
- ls
- git clone https://github.com/SFML/SFML.git
- cd SFML
- mkdir SFMLInstall
- mkdir SFMLBuild
- cd SFMLBuild
- cmake -DCMAKE_INSTALL_PREFIX="../SFMLInstall" ..
- make
- make install
- cd ../../
script:
- pwd
- ls
- cmake --version
- mkdir build
- cd build
- cmake -DSFML_DIR="../SFML/SFMLInstall/lib/cmake/SFML" ..
- make
- tests/EnlivengineTests