language: cpp
compiler: gcc

dist: bionic

addons:
  apt:
    packages:
      - gcc-7
      - g++-7

script:
  - pwd
  - ls
  - cmake --version
  - rm -rf ./build
  - mkdir build
  - cd build
  - pwd
  - cmake ..
  - ls
  - make
  - ls
  - example/EnlivengineExample
  - tests/EnlivengineTests
  - cd ..
  - rm -rf ./build
