# See: https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
    
name: CI

on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - {
            name: "Windows MSVC",
            image: windows-latest,
            os: windows,
            cc: cl,
            cxx: cl
          }
        - {
            name: "Ubuntu GCC",
            image: ubuntu-latest,
            os: ubuntu,
            cc: gcc-9,
            cxx: g++-9
          }
        - {
            name: "MacOS Clang",
            image: macos-latest,
            os: macos,
            cc: clang,
            cxx: clang++
          }
        config:
        - {
            name: "Tool",
            cfg: Debug 
          }
        - {
            name: "Debug",
            cfg: RelWithDebInfo
          }
        - {
            name: "Release",
            cfg: Release
          }
          
    name: ${{ matrix.platform.name }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.image }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: bash ./EnlivengineEnv/Dependencies.sh
      
    - name: GenerateProject
      run: bash ./EnlivengineEnv/GenerateProject.sh ${{ matrix.platform.cc }} ${{ matrix.platform.cxx }}
      
    - name: BuildMain
      run: bash ./EnlivengineEnv/BuildMain.sh ${{ matrix.config.cfg }}
      
    - name: Tests
      run: bash ./EnlivengineEnv/Tests.sh ${{ matrix.config.cfg }}
      
    - name: Deploy 3DSceneExample
      run: bash ./EnlivengineEnv/DeployFTP.sh ${{ secrets.deploy_server }} ${{ secrets.deploy_port }} ${{ secrets.deploy_username }} ${{ secrets.deploy_password }} "3DSceneExample" "$GITHUB_REF" ${{ matrix.config.name }} "$GITHUB_RUN_ID" "EnlivengineExamples" ${{ matrix.config.cfg }} "builds/"
