# See: https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
    
name: CI
on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.yml'
    - 'Assets/**'
    - '.gitattributes'
    - '.gitignore'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - {
            name: "Windows MSVC",
            image: windows-latest,
            os: windows,
            cc: cl,
            cxx: cl
          }
        - {
            name: "Ubuntu GCC",
            image: ubuntu-latest,
            os: ubuntu,
            cc: gcc-9,
            cxx: g++-9
          }
        - {
            name: "MacOS Clang",
            image: macos-latest,
            os: macos,
            cc: clang,
            cxx: clang++
          }
        config:
        - {
            name: "Tool",
            cfg: Debug 
          }
        - {
            name: "Debug",
            cfg: RelWithDebInfo
          }
        - {
            name: "Release",
            cfg: Release
          }
          
    name: ${{ matrix.platform.name }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.image }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: InstallDependencies
      run: bash ./EnlivengineEnv/InstallDependencies.sh
      
    - name: GenerateProject
      run: bash ./EnlivengineEnv/GenerateProject.sh ${{ matrix.platform.cc }} ${{ matrix.platform.cxx }}
      
    - name: BuildEnlivengine
      run: bash ./EnlivengineEnv/BuildEnlivengine.sh ${{ matrix.config.cfg }}
      
    - name: RunTests
      run: bash ./EnlivengineEnv/RunTests.sh ${{ matrix.config.cfg }}
      
    - name: Deploy 3DSceneExample
      continue-on-error: true
      run: bash ./EnlivengineEnv/DeployProject.sh ${{ secrets.deploy_server }} ${{ secrets.deploy_port }} ${{ secrets.deploy_username }} ${{ secrets.deploy_password }} "3DSceneExample" ${{ github.ref }} ${{ matrix.config.name }} ${{ github.run_id }} "EnlivengineExamples/" ${{ matrix.config.cfg }} ${{ secrets.deploy_distantPath }}
