# See: https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
    
name: CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - {
            name: "Windows MSVC",
            os: windows-latest,
            cc: "cl",
            cxx: "cl"
          }
        - {
            name: "Ubuntu GCC",
            os: ubuntu-latest,
            cc: "gcc-9",
            cxx: "g++-9"
          }
        - {
            name: "MacOS Clang",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++"
          }
          
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install dependencies
      run: |
          bash ./EnlivengineEnv/Dependencies.sh
          export CXX=${{ matrix.platform.cxx }} CC=${{ matrix.platform.cc }}
      
    - name: GenerateProject
      run: bash ./EnlivengineEnv/GenerateProject.sh
      
    - name: BuildAll
      run: bash ./EnlivengineEnv/BuildAll.sh
      
    - name: Tests
      run: bash ./EnlivengineEnv/Tests.sh
