# See: https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
    
name: CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - {
            name: "Windows MSVC",
            os: windows-latest
          }
        - {
            name: "Ubuntu GCC",
            os: ubuntu-latest
          }
        - {
            name: "MacOS Clang",
            os: macos-latest
          }
          
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install dependencies
      run: bash ./EnlivengineEnv/Dependencies.sh
      
    - name: GenerateProject
      run: bash ./EnlivengineEnv/GenerateProject.sh
      
    - name: BuildAll
      run: bash ./EnlivengineEnv/BuildAll.sh
      
    - name: Tests
      run: bash ./EnlivengineEnv/Tests.sh
