# See: https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
    
name: CMake

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - {
            name: "Windows MSVC",
            image: windows-latest,
            os: windows,
            cc: cl,
            cxx: cl
          }
        - {
            name: "Ubuntu GCC",
            image: ubuntu-latest,
            os: ubuntu,
            cc: gcc-9,
            cxx: g++-9
          }
        - {
            name: "MacOS Clang",
            image: macos-latest,
            os: macos,
            cc: clang,
            cxx: clang++
          }
        config: [Debug, RelWithDebInfo, Release]
          
    name: ${{ matrix.platform.name }}-${{ matrix.config }}
    runs-on: ${{ matrix.platform.image }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: bash ./EnlivengineEnv/Dependencies.sh
      
    - name: GenerateProject
      run: bash ./EnlivengineEnv/GenerateProject.sh ${{ matrix.platform.cc }} ${{ matrix.platform.cxx }}
      
    - name: BuildMain
      run: bash ./EnlivengineEnv/BuildMain.sh ${{ matrix.config }}
      
    - name: Tests
      run: bash ./EnlivengineEnv/Tests.sh ${{ matrix.config }}
      
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.deploy_server }}
        port: ${{ secrets.deploy_port }}
        username: ${{ secrets.deploy_username }}
        password: ${{ secrets.deploy_password }}
        local-dir: ./build/EnlivengineExamples/${{ matrix.config }}/
        server-dir: ./${{ matrix.platform }}/${{ matrix.config }}/
