# See: https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
    
name: CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - {
            name: "Windows MSVC",
            os: windows-latest,
            cc: cl,
            cxx: cl
          }
        - {
            name: "Ubuntu GCC",
            os: ubuntu-latest,
            cc: gcc-9,
            cxx: g++-9
          }
        - {
            name: "MacOS Clang",
            os: macos-latest,
            cc: clang,
            cxx: clang++
          }
        config: [Debug, RelWithDebInfo, Release]
          
    name: ${{ matrix.platform.name }}-${{ matrix.config }}
    runs-on: ${{ matrix.platform.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: bash ./EnlivengineEnv/Dependencies.sh
      
    - name: GenerateProject
      run: bash ./EnlivengineEnv/GenerateProject.sh ${{ matrix.platform.cc }} ${{ matrix.platform.cxx }}
      
    - name: BuildMain
      run: bash ./EnlivengineEnv/BuildMain.sh ${{ matrix.config }}
      
    - name: Tests
      run: bash ./EnlivengineEnv/Tests.sh ${{ matrix.config }}
