# See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
# See: https://github.com/actions/starter-workflows/issues/53
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake.yml
    
name: CMake

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: InstallDependencies
        run: sudo apt-get install gcc-9 g++-9 libgl1-mesa-dev cmake
      - name: GenerateProject
        run: bash ./EnlivengineEnv/GenerateProject.sh

    
    
